@supabase-api-key = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6dG5ubm9raW16YW9kbXVyenBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NDg2NDYsImV4cCI6MjA2MTAyNDY0Nn0.E2tTM5bo0VQy4Cy0iHJZ0XKUbKN99f4CnKpEO3Sm0qY


### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
### Test protected endpoint
GET http://localhost:8080/interviews
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}


###
GET http://localhost:8080/interviews/upcoming/count
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}


###
GET http://localhost:8080/interviews/27f57d9c-9ce4-46ec-95a0-95ad53a763fe1
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}


###
# @name Andre's first interview
POST http://localhost:8080/interviews
Content-Type: application/json
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

{
  "user_id": "7129f9e8-06f5-4879-a7c2-4ddfab12e0f5",
  "format": "in-person",
  "round": "technical screen",
  "date": "April 1, 2025",
  "time": "11:30 AM"
}

###
# @name Andre's second interview
POST http://localhost:8080/interviews
Content-Type: application/json
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

{
  "user_id": "7129f9e8-06f5-4879-a7c2-4ddfab12e0f5",
  "format": "virtual",
  "round": "HR phone screen",
  "date": "April 1, 2025",
  "time": "12:30 PM"
}

###
# @name update Andre's first interview
PUT http://localhost:8080/interviews/d1802dae-4891-49e7-a9b2-918e3b9842ce
Content-Type: application/json
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

{
  "id": "d1802dae-4891-49e7-a9b2-918e3b9842ce",
  "user_id": "3ed484ad-7bac-4906-b56c-994b325865f2",
  "format": "in-person",
  "round": "final chat",
  "date": "April 10, 2025",
  "time": "10:00 AM"
}

###
DELETE http://localhost:8080/interviews/d2647fbf-deaa-41c3-9885-446fe97cfb1a1
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}
Content-Type: application/json


###
GET http://localhost:8080/interviews/search/
Authorization: Bearer {{auth-token}}
apikey:  {{supabase-api-key}}
