@deddecco-jwt = eyJhbGciOiJIUzI1NiIsImtpZCI6IkpWeEJ2bWx5Tk5XcHpkdU0iLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL25ldXVydWR2cW91emVmaHZ1Z3p0LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJkMjQzNjkxNC1mYzE1LTQ0Y2QtOTJlZi0yZWYxODc4NjdmZTQiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQyNTE2NzI5LCJpYXQiOjE3NDI1MTMxMjksImVtYWlsIjoic3BvbmdlYm9iQG1haWxpbmF0b3IuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NDI1MTMxMjl9XSwic2Vzc2lvbl9pZCI6IjYyMjJkOTNhLWQyZjQtNDVkMi05ZWUxLWZiMzM3OWUzYmZkNSIsImlzX2Fub255bW91cyI6ZmFsc2V9.I1wXkdaYmEvLqlQgQ3pkm5cpoBukj4mFcAzfYcepiEk
@supabase-api-key = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ldXVydWR2cW91emVmaHZ1Z3p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNzI2MTEsImV4cCI6MjA1NTY0ODYxMX0.5LcQWLhCQn8vsuL6wmeQ3RUvM6fG6lOljlidxPlzebc

###
GET http://localhost:8080/jobs
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

###
GET http://localhost:8080/jobs/search/?status=Rejected
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

###
GET http://localhost:8080/jobs/status-counts
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}


###
# @name Andre's first job
POST http://localhost:8080/jobs
Content-Type: application/json
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

{
  "title": "Software Engineer I",
  "level": "Entry Level",
  "minSalary": 60000,
  "maxSalary": 100000,
  "location": "New York",
  "status": "Applied",
  "userId": "3ed484ad-7bac-4906-b56c-994b325865f2"
}

###
# @name Andre's second job
POST http://localhost:8080/jobs
Content-Type: application/json
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

{
  "title": "Reliability Engineer II",
  "level": "Mid-Level",
  "minSalary": 66550,
  "maxSalary": 87500,
  "location": "Philadelphia",
  "status": "Applied",
  "userId": "3ed484ad-7bac-4906-b56c-994b325865f2"
}

###
# @name Andre's third job
POST http://localhost:8080/jobs
Content-Type: application/json
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

{
  "title": "Technical Manager",
  "level": "Mid-level",
  "minSalary": 89700,
  "maxSalary": 102300,
  "location": "Hartford",
  "status": "Rejected",
  "userId": "3ed484ad-7bac-4906-b56c-994b325865f2"
}

###
# @name updating Andre 3.0
PUT http://localhost:8080/jobs
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}
Content-Type: application/json

{
  "id": "9cd61496-6913-4a9c-a946-5934ee4ac7b8",
  "title": "Reliability Engineer I",
  "level": "Entry Level",
  "minsalary": 56000,
  "maxsalary": 875000,
  "location": "Philadelphia",
  "status": "Applied",
  "user_id": "3ed484ad-7bac-4906-b56c-994b325865f2"
}

###
# @name updating Andre 2.0
PUT http://localhost:8080/jobs
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}
Content-Type: application/json

{
  "id": "6d974ffc-ec97-4cf6-8e04-b1ecd81767d4",
  "title": "Reliability Engineer I",
  "level": "Entry Level",
  "minsalary": 56000,
  "maxsalary": 75000,
  "location": "Lancaster",
  "status": "Offer",
  "user_id": "3ed484ad-7bac-4906-b56c-994b325865f2"
}


###
PUT http://localhost:8080/jobs/36ee1574-f02f-4f86-9e8e-b1ed6832cbee
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "id": "36ee1574-f02f-4f86-9e8e-b1ed6832cbee",
  "title": "Reliability Engineer I",
  "level": "Entry Level",
  "minSalary": 123456,
  "maxSalary": 126543,
  "location": "Philadelphia",
  "status": "Applied",
  "userId": "3ed484ad-7bac-4906-b56c-994b325865f2"
}

###
#@name delete Andre's job
DELETE http://localhost:8080/jobs/3701b54d-c50a-42d7-8d33-5ea3fbac1116
Content-Type: application/json
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}


### test status counter
GET http://localhost:8080/jobs/status-counts
Authorization: Bearer {{auth-token}}


### Test protected endpoint
GET http://localhost:8080/jobs
Authorization: Bearer {{auth-token}}

###
GET https://neuurudvqouzefhvugzt.supabase.co/rest/v1/job
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}