@deddecco-jwt = eyJhbGciOiJIUzI1NiIsImtpZCI6IkpWeEJ2bWx5Tk5XcHpkdU0iLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL25ldXVydWR2cW91emVmaHZ1Z3p0LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJkMjQzNjkxNC1mYzE1LTQ0Y2QtOTJlZi0yZWYxODc4NjdmZTQiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQyNTE2NzI5LCJpYXQiOjE3NDI1MTMxMjksImVtYWlsIjoic3BvbmdlYm9iQG1haWxpbmF0b3IuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NDI1MTMxMjl9XSwic2Vzc2lvbl9pZCI6IjYyMjJkOTNhLWQyZjQtNDVkMi05ZWUxLWZiMzM3OWUzYmZkNSIsImlzX2Fub255bW91cyI6ZmFsc2V9.I1wXkdaYmEvLqlQgQ3pkm5cpoBukj4mFcAzfYcepiEk
@supabase-api-key = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ldXVydWR2cW91emVmaHZ1Z3p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNzI2MTEsImV4cCI6MjA1NTY0ODYxMX0.5LcQWLhCQn8vsuL6wmeQ3RUvM6fG6lOljlidxPlzebc

###
GET http://localhost:8080/jobs
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

###
GET http://localhost:8080/jobs/6d45dedd-4c75-40ed-af30-2251b2d37ffa1
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

###
GET http://localhost:8080/jobs/search/?status=Rejected
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

###
GET http://localhost:8080/jobs/search
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

###
GET http://localhost:8080/jobs/status-counts
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}


###
# @name Andre's first job
POST http://localhost:8080/jobs
Content-Type: application/json
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

{
  "title": "Software Engineer I",
  "level": "Entry Level",
  "minSalary": 60000,
  "maxSalary": 100000,
  "location": "New York",
  "status": "Applied",
  "user_id": "7129f9e8-06f5-4879-a7c2-4ddfab12e0f5"
}

###
# @name Andre's second job
POST http://localhost:8080/jobs
Content-Type: application/json
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

{
  "title": "Reliability Engineer II",
  "level": "Mid-Level",
  "minSalary": 66550,
  "maxSalary": 87500,
  "location": "Philadelphia",
  "status": "Applied",
  "user_id": "7129f9e8-06f5-4879-a7c2-4ddfab12e0f5"
}

###
# @name Andre's third job
POST http://localhost:8080/jobs
Content-Type: application/json
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

{
  "title": "Scrum Master",
  "level": "Senior",
  "minSalary": 150000,
  "maxSalary": 150000,
  "location": "Hoboken",
  "status": "Hired",
  "user_id": "3ed484ad-7bac-4906-b56c-994b325865f2"
}


###
# @name updating Andre 3.0
PUT http://localhost:8080/jobs
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}
Content-Type: application/json

{
  "id": "9cd61496-6913-4a9c-a946-5934ee4ac7b8",
  "title": "Reliability Engineer I",
  "level": "Entry Level",
  "minsalary": 56000,
  "maxsalary": 875000,
  "location": "Philadelphia",
  "status": "Applied",
  "user_id": "3ed484ad-7bac-4906-b56c-994b325865f2"
}

###
# @name updating Andre 2.0
PUT http://localhost:8080/jobs
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}
Content-Type: application/json

{
  "id": "6d974ffc-ec97-4cf6-8e04-b1ecd81767d4",
  "title": "Reliability Engineer I",
  "level": "Entry Level",
  "minsalary": 56000,
  "maxsalary": 75000,
  "location": "Lancaster",
  "status": "Offer",
  "user_id": "3ed484ad-7bac-4906-b56c-994b325865f2"
}


###
PUT http://localhost:8080/jobs/e8623894-0834-46fd-94ec-a176b80c13b7
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "id": "e8623894-0834-46fd-94ec-a176b80c13b7",
  "title": "Software Engineer III",
  "level": "Entry Level",
  "minsalary": 99800,
  "maxsalary": 123700,
  "location": "New York",
  "status": "Hired",
  "userId": "3ed484ad-7bac-4906-b56c-994b325865f2"
}

###
#@name delete Andre's job
DELETE http://localhost:8080/jobs/pepperonipizza
Content-Type: application/json
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}


### test status counter
GET http://localhost:8080/jobs/search/?status=Applied&location=New%20York
Authorization: Bearer {{auth-token}}
apikey:  {{supabase-api-key}}


### Test protected endpoint
GET http://localhost:8080/jobs
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

###
GET https://neuurudvqouzefhvugzt.supabase.co/rest/v1/job
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}