@deddecco-jwt = eyJhbGciOiJIUzI1NiIsImtpZCI6IkpWeEJ2bWx5Tk5XcHpkdU0iLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL25ldXVydWR2cW91emVmaHZ1Z3p0LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJkMjQzNjkxNC1mYzE1LTQ0Y2QtOTJlZi0yZWYxODc4NjdmZTQiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQyNTE2NzI5LCJpYXQiOjE3NDI1MTMxMjksImVtYWlsIjoic3BvbmdlYm9iQG1haWxpbmF0b3IuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NDI1MTMxMjl9XSwic2Vzc2lvbl9pZCI6IjYyMjJkOTNhLWQyZjQtNDVkMi05ZWUxLWZiMzM3OWUzYmZkNSIsImlzX2Fub255bW91cyI6ZmFsc2V9.I1wXkdaYmEvLqlQgQ3pkm5cpoBukj4mFcAzfYcepiEk
@supabase-api-key = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6dG5ubm9raW16YW9kbXVyenBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NDg2NDYsImV4cCI6MjA2MTAyNDY0Nn0.E2tTM5bo0VQy4Cy0iHJZ0XKUbKN99f4CnKpEO3Sm0qY

###
GET http://localhost:8080/jobs
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

###
GET http://localhost:8080/jobs/favorites
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

###
GET http://localhost:8080/jobs/ac34e641-5ca5-41a0-89f6-5fb05a37819a
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

###
GET http://localhost:8080/jobs/search/?status=Applied
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

###
GET http://localhost:8080/jobs/search
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

###
GET http://localhost:8080/jobs/status-counts
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}


###
# @name Andre's first job
POST http://localhost:8080/jobs
Content-Type: application/json
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

{
  "title": "Software Engineer III",
  "level": "Mid-level",
  "minSalary": 90000,
  "maxSalary": 100000,
  "location": "Richmond",
  "status": "Accepted"
}

###
# @name Andre's second job
POST http://localhost:8080/jobs
Content-Type: application/json
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

{
  "title": "Reliability Engineer II",
  "level": "Mid-Level",
  "minSalary": 66550,
  "maxSalary": 87500,
  "location": "Philadelphia",
  "status": "Applied",
  "user_id": "7129f9e8-06f5-4879-a7c2-4ddfab12e0f5"
}

###
# @name Andre's third job
POST http://localhost:8080/jobs
Content-Type: application/json
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

{
  "title": "Scrum Master",
  "level": "Senior",
  "minSalary": 150000,
  "maxSalary": 150000,
  "location": "Hoboken",
  "status": "Accepted",
  "user_id": "3ed484ad-7bac-4906-b56c-994b325865f2"
}


###
# @name updating Andre 3.0
PUT http://localhost:8080/jobs/775dc85f-2445-46a4-a65a-878813cf2069
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}
Content-Type: application/json

{
  "id": "775dc85f-2445-46a4-a65a-878813cf2069",
  "title": "Software Engineer III",
  "level": "Mid-level",
  "minSalary": 95000,
  "maxSalary": 95000,
  "location": "Richmond",
  "status": "Accepted",
  "company": "ABC, Inc.",
  "userId": "3ed484ad-7bac-4906-b56c-994b325865f2",
  "lastModified": "2025-04-16T20:24:35.71559Z",
  "favorite": false
}

###
# @name updating Andre 2.0
PUT http://localhost:8080/jobs
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}
Content-Type: application/json

{
  "id": "6d974ffc-ec97-4cf6-8e04-b1ecd81767d4",
  "title": "Reliability Engineer I",
  "level": "Entry Level",
  "minsalary": 56000,
  "maxsalary": 75000,
  "location": "Lancaster",
  "status": "Offer",
  "user_id": "3ed484ad-7bac-4906-b56c-994b325865f2"
}


###
PUT http://localhost:8080/jobs/e8623894-0834-46fd-94ec-a176b80c13b7
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
  "id": "e8623894-0834-46fd-94ec-a176b80c13b7",
  "title": "Software Engineer III",
  "level": "Entry Level",
  "minsalary": 99800,
  "maxsalary": 123700,
  "location": "New York",
  "status": "Accepted",
  "userId": "3ed484ad-7bac-4906-b56c-994b325865f2"
}

###
#@name delete Andre's job
DELETE http://localhost:8080/jobs/775dc85f-2445-46a4-a65a-878813cf2069
Content-Type: application/json
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}


### test status counter
GET http://localhost:8080/jobs/search/?status=Applied&location=New%20York
Authorization: Bearer {{auth-token}}
apikey:  {{supabase-api-key}}


### Test protected endpoint
GET http://localhost:8080/jobs/search/?title=Software%20Engineer%20I
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}

###
GET https://neuurudvqouzefhvugzt.supabase.co/rest/v1/job
Authorization: Bearer {{auth-token}}
apikey: {{supabase-api-key}}