@basic-password = 90b799ea-c60b-48fc-8436-7ef1b4cd4e34
@deddecco-jwt = eyJhbGciOiJIUzI1NiIsImtpZCI6IkpWeEJ2bWx5Tk5XcHpkdU0iLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL25ldXVydWR2cW91emVmaHZ1Z3p0LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJkMjQzNjkxNC1mYzE1LTQ0Y2QtOTJlZi0yZWYxODc4NjdmZTQiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQwNTM0MjAwLCJpYXQiOjE3NDA1MzA2MDAsImVtYWlsIjoic3BvbmdlYm9iQG1haWxpbmF0b3IuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3NDA1MzA2MDB9XSwic2Vzc2lvbl9pZCI6IjgxZWFhNTkwLTEyMjEtNGJhNy05M2JjLTFhMzU5YjAyZmYxNyIsImlzX2Fub255bW91cyI6ZmFsc2V9.EGVF_mXrXKGgOoeQUxezf-bk6ptlfcctOitv9gxwbGs

###
# @name Get current time
GET http://localhost:8080/time/current
Authorization: Basic user {{basic-password}}

###
# @name Get current time (JWT)
GET http://localhost:8080/time/current
Authorization: Bearer {{deddecco-jwt}}

###
#
POST http://localhost:8080/time/my-timezone
Content-Type: application/json

{
  "timeZone": "GMT-05:00"
}

###
GET http://localhost:8080/profiles/current
Authorization: Basic user {{basic-password}}

###
GET http://localhost:8080/profiles/2a77f495-3307-4176-be02-421f321afcb4
Authorization: Bearer {{deddecco-jwt}}


###
GET http://localhost:8080/profile/view
Authorization: Bearer {{deddecco-jwt}}


###
POST http://localhost:8080/profiles
Content-Type: application/json

{
  "name": "John Smith",
  "email": "john.smith@example.com",
  "currentTitle": "Software Engineer",
  "bio": "This is John's bio.",
  "location": "New York, USA"
}

###
PUT http://localhost:8080/profiles/current
Content-Type: application/json
Authorization: Bearer {{deddecco-jwt}}

{
  "user_id": "02ba21b1-4432-4267-a5ca-639774679244",
  "name": "Ellie Wilson",
  "email": "ellie@ellie.com",
  "title": "Software Reliability Engineer II",
  "bio": "writing code fueled by coffee since 2017",
  "location": "Remote"
}

###
PUT http://localhost:8080/profiles/02ba21b1-4432-4267-a5ca-639774679245
Content-Type: application/json

{
"user_id": "02ba21b1-4432-4267-a5ca-639774679245",
"name": "Ellie Smith",
"email": "ellie@ellie.com",
"title": "Software Reliability Engineer II",
"bio": "writing code fueled by coffee since 2017",
"location": "Remote/US"
}