@basic-password = c76bf3d5-e82d-41dd-a703-29e41ea1a23d

###
# @name Get current time
GET http://localhost:8080/time/current
Authorization: Basic user {{basic-password}}

###
#
POST http://localhost:8080/time/my-timezone
Content-Type: application/json

{
  "timeZone": "GMT-05:00"
}

###
GET http://localhost:8080/profiles/current
Authorization: Basic user {{basic-password}}

###
GET http://localhost:8080/profiles/2a77f495-3307-4176-be02-421f321afcb4

###
GET http://localhost:8080/profile/view

###
POST http://localhost:8080/profiles
Content-Type: application/json

{
  "name": "John Smith",
  "email": "john.smith@example.com",
  "currentTitle": "Software Engineer",
  "bio": "This is John's bio.",
  "location": "New York, USA"
}

###
PUT http://localhost:8080/profiles/current
Content-Type: application/json

{
  "user_id": "02ba21b1-4432-4267-a5ca-639774679244",
  "name": "Ellie Wilson",
  "email": "ellie@ellie.com",
  "title": "Software Reliability Engineer II",
  "bio": "writing code fueled by coffee since 2017",
  "location": "Remote"
}

###
PUT http://localhost:8080/profiles/02ba21b1-4432-4267-a5ca-639774679245
Content-Type: application/json

{
"user_id": "02ba21b1-4432-4267-a5ca-639774679245",
"name": "Ellie Smith",
"email": "ellie@ellie.com",
"title": "Software Reliability Engineer II",
"bio": "writing code fueled by coffee since 2017",
"location": "Remote/US"
}