spring:
  application:
    name: jobtracker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://neuurudvqouzefhvugzt.supabase.co/auth/v1/jwks
logging:
  level:
    edu.uis.csc478.sp25.jobtracker: DEBUG
    org.springframework.security: DEBUG
